import React from 'react';
import { GeneratedReport, ReportFilters } from '../../types';

export interface ReportPrintContextInfo {
  studyCode?: string;
  studyTitle?: string;
  protocolVersion?: string;
  siteCode?: string;
  siteName?: string;
  piName?: string;
  piRole?: string;
}

interface ReportPrintDocumentProps {
  report: GeneratedReport;
  contextInfo?: ReportPrintContextInfo;
}

export const formatFilterDisplay = (filters?: ReportFilters): string => {
  if (!filters || Object.keys(filters).length === 0) return 'All Records (No active filters)';
  const parts: string[] = [];
  if (filters.search) parts.push(`Search: "${filters.search}"`);
  if (filters.status) parts.push(`Status: ${filters.status}`);
  if (filters.category) parts.push(`Category: ${filters.category}`);
  if (filters.classification) parts.push(`Classification: ${filters.classification}`);
  if (filters.priority) parts.push(`Priority: ${filters.priority}`);
  if (filters.reviewStatus) parts.push(`Review: ${filters.reviewStatus}`);
  if (filters.dateFrom || filters.dateTo) {
    parts.push(`Date: ${filters.dateFrom || 'Any'} to ${filters.dateTo || 'Any'}`);
  }
  return parts.length > 0 ? parts.join(' | ') : 'All Records';
};

export const ReportPrintDocument: React.FC<ReportPrintDocumentProps> = ({
  report,
  contextInfo = {},
}) => {
  const {
    studyCode = report.metadata.studyId,
    studyTitle = 'Ayurvedic Clinical Protocol Study',
    protocolVersion = 'v2.1',
    siteCode = report.metadata.siteId,
    siteName = 'All India Institute of Ayurveda Main Hospital',
    piName = 'Dr. Arvind Sharma',
    piRole = 'Principal Investigator',
  } = contextInfo;

  const generatedDateFormatted = new Date(report.metadata.generatedAt).toLocaleString('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'medium',
  });

  return (
    <div
      id="ctms-printable-report"
      className="bg-white text-slate-900 p-6 sm:p-8 font-sans max-w-full"
    >
      {/* 1. INSTITUTION & SYSTEM HEADER */}
      <div className="border-b-2 border-slate-800 pb-4 mb-4">
        <div className="flex items-start justify-between gap-4">
          <div>
            <h1 className="text-lg font-bold uppercase tracking-wider text-slate-900 font-serif">
              All India Institute of Ayurveda (AIIA)
            </h1>
            <h2 className="text-xs font-semibold tracking-wide text-slate-600 uppercase">
              Clinical Trial Management System (CTMS) — Operational Dossier
            </h2>
          </div>
          <div className="text-right">
            <span className="inline-block px-2.5 py-0.5 text-[11px] font-bold tracking-wider uppercase bg-slate-100 border border-slate-300 text-slate-800 rounded-xs">
              {report.metadata.reportType}
            </span>
            <p className="text-[10px] text-slate-500 mt-1">
              Doc ID: {report.metadata.reportType}-{studyCode}-{siteCode}
            </p>
          </div>
        </div>

        <div className="mt-3">
          <h2 className="text-xl font-bold text-slate-900 font-serif">
            {report.metadata.title}
          </h2>
        </div>
      </div>

      {/* 2. WHERE & WHEN: DATA SOURCE & AUDIT METADATA GRID */}
      <div className="bg-slate-50 border border-slate-300 rounded-xs p-3 mb-5 text-xs text-slate-800">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-y-2 gap-x-4">
          <div>
            <span className="font-semibold text-slate-600 block text-[10px] uppercase">
              Study / Protocol
            </span>
            <span className="font-medium text-slate-900">
              {studyCode} ({protocolVersion})
            </span>
            <span className="text-[11px] text-slate-500 block truncate" title={studyTitle}>
              {studyTitle}
            </span>
          </div>

          <div>
            <span className="font-semibold text-slate-600 block text-[10px] uppercase">
              Investigator Site / Facility
            </span>
            <span className="font-medium text-slate-900">{siteCode}</span>
            <span className="text-[11px] text-slate-500 block truncate" title={siteName}>
              {siteName}
            </span>
          </div>

          <div>
            <span className="font-semibold text-slate-600 block text-[10px] uppercase">
              Generated Date & Time
            </span>
            <span className="font-medium text-slate-900">{generatedDateFormatted}</span>
            <span className="text-[10px] text-slate-500 block">Time Zone: IST (UTC+05:30)</span>
          </div>

          <div>
            <span className="font-semibold text-slate-600 block text-[10px] uppercase">
              Generated By / Role
            </span>
            <span className="font-medium text-slate-900">{piName}</span>
            <span className="text-[11px] text-slate-500 block">
              {piRole} ({report.metadata.generatedBy || 'Authorised Investigator'})
            </span>
          </div>
        </div>

        <div className="mt-2.5 pt-2.5 border-t border-slate-200 grid grid-cols-1 md:grid-cols-3 gap-2 text-[11px]">
          <div>
            <span className="font-semibold text-slate-700">Data Source Register: </span>
            <span className="text-slate-600">CTMS Operational {report.metadata.reportType} Dataset</span>
          </div>
          <div>
            <span className="font-semibold text-slate-700">Applied Filter Scope: </span>
            <span className="text-slate-600">{formatFilterDisplay(report.filters)}</span>
          </div>
          <div className="text-left md:text-right">
            <span className="font-semibold text-slate-700">Records in Dossier: </span>
            <span className="font-bold text-slate-900">{report.totalRows} record(s)</span>
          </div>
        </div>

        {/* Regulatory Governance Banner */}
        <div className="mt-2.5 pt-2 border-t border-amber-200 text-[10.5px] text-amber-900 bg-amber-50/80 p-2 rounded-xs">
          <span className="font-bold">Regulatory Operational Disclaimer: </span>
          <span>{report.metadata.disclaimer}</span>
        </div>
      </div>

      {/* 3. SUMMARY METRICS STRIP */}
      {report.summaryMetrics.length > 0 && (
        <div className="mb-4">
          <div className="text-[11px] font-bold uppercase tracking-wider text-slate-700 mb-1.5">
            Operational Summary Metrics
          </div>
          <div className="grid grid-cols-3 sm:grid-cols-6 gap-2">
            {report.summaryMetrics.map((metric, idx) => (
              <div
                key={`${metric.label}-${idx}`}
                className="bg-slate-100 border border-slate-300 p-2 rounded-xs text-center"
              >
                <div className="text-xs font-bold text-slate-900">{metric.value}</div>
                <div className="text-[10px] text-slate-600 truncate" title={metric.label}>
                  {metric.label}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 4. EXCEL-LIKE TABULAR DATA GRID */}
      <div className="mb-6 overflow-x-auto">
        <table className="w-full border-collapse border border-slate-400 text-xs text-slate-800">
          <thead>
            <tr className="bg-slate-200 text-slate-900 border-b border-slate-400">
              <th className="border border-slate-400 px-2 py-1.5 text-center text-[10px] font-bold w-10">
                #
              </th>
              {report.columns.map((col) => (
                <th
                  key={col.key}
                  className="border border-slate-400 px-2.5 py-1.5 text-left text-[11px] font-bold tracking-tight uppercase"
                >
                  {col.label}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {report.rows.length === 0 ? (
              <tr>
                <td
                  colSpan={report.columns.length + 1}
                  className="border border-slate-300 py-6 text-center text-slate-500 italic"
                >
                  No clinical trial records match the selected scope and criteria.
                </td>
              </tr>
            ) : (
              report.rows.map((row, idx) => (
                <tr
                  key={idx}
                  className={idx % 2 === 0 ? 'bg-white' : 'bg-slate-50/80'}
                >
                  <td className="border border-slate-300 px-2 py-1 text-center font-mono text-[10px] text-slate-500">
                    {idx + 1}
                  </td>
                  {report.columns.map((col) => {
                    const rawVal = row[col.key];
                    let displayVal = '—';
                    if (rawVal !== null && rawVal !== undefined) {
                      if (typeof rawVal === 'boolean') {
                        displayVal = rawVal ? 'YES' : 'NO';
                      } else {
                        displayVal = String(rawVal);
                      }
                    }

                    const isCodeOrId =
                      col.key.toLowerCase().includes('id') ||
                      col.key.toLowerCase().includes('code');

                    return (
                      <td
                        key={col.key}
                        className={`border border-slate-300 px-2.5 py-1.5 text-[11px] ${
                          isCodeOrId ? 'font-mono text-slate-900 font-semibold' : ''
                        }`}
                      >
                        {displayVal}
                      </td>
                    );
                  })}
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* 5. AUTHORISED SIGNATORY & OPERATIONAL REVIEW FOOTER */}
      <div className="border border-slate-400 rounded-xs p-4 bg-slate-50/50 break-inside-avoid">
        <div className="text-xs font-bold uppercase tracking-wider text-slate-900 mb-1">
          Authorised Signatory & Operational Review Verification
        </div>
        <p className="text-[11px] text-slate-600 mb-4 leading-relaxed">
          I hereby certify that I have reviewed the operational clinical trial data presented in this
          report. The records extracted above faithfully reflect the active status within the AIIA
          Clinical Trial Management System for Study{' '}
          <span className="font-semibold text-slate-800">{studyCode}</span> at Site{' '}
          <span className="font-semibold text-slate-800">{siteCode}</span> as of the generation timestamp.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-3 border-t border-slate-300">
          {/* Signature Line */}
          <div className="space-y-1">
            <div className="h-10 border-b border-slate-800 flex items-end">
              <span className="text-[10px] text-slate-400 italic">Signature</span>
            </div>
            <div className="text-xs font-bold text-slate-900">{piName}</div>
            <div className="text-[11px] text-slate-600">{piRole}</div>
            <div className="text-[10px] text-slate-500">ID: {report.metadata.generatedBy || 'Authorised Investigator'}</div>
          </div>

          {/* Date & Facility */}
          <div className="space-y-1">
            <div className="h-10 border-b border-slate-800 flex items-end">
              <span className="text-[10px] text-slate-400 italic">Date of Verification</span>
            </div>
            <div className="text-xs font-bold text-slate-900">
              Date: _________________________
            </div>
            <div className="text-[11px] text-slate-600">Facility: {siteName}</div>
            <div className="text-[10px] text-slate-500">Site Code: {siteCode}</div>
          </div>

          {/* Official Stamp Box */}
          <div className="border border-dashed border-slate-400 rounded-xs h-24 flex flex-col items-center justify-center p-2 text-center bg-white">
            <span className="text-[10px] uppercase font-bold text-slate-400">
              Institutional / Site Seal
            </span>
            <span className="text-[9px] text-slate-400 mt-1">
              (Affix official department stamp here)
            </span>
          </div>
        </div>

        {/* System Imprint */}
        <div className="mt-4 pt-2 border-t border-slate-200 flex justify-between items-center text-[9px] text-slate-400">
          <span>AIIA-CTMS Regulatory Export Engine • Build 2026.09</span>
          <span>Confidential — Clinical Trial Investigational Record</span>
        </div>
      </div>
    </div>
  );
};
