"""initial_cro_sponsor_schema

Revision ID: 35f75b6f0684
Revises: 
Create Date: 2026-10-05 17:30:05.528462

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '35f75b6f0684'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_type', sa.Enum('cro', 'sponsor', 'institution', 'site_affiliate', name='organization_type', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'active', 'suspended', 'deactivated', name='organization_status', create_constraint=True), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("organization_type IN ('cro', 'sponsor', 'institution', 'site_affiliate')", name='organization_type'),
    sa.CheckConstraint("organization_type IN ('cro', 'sponsor', 'institution', 'site_affiliate')", name='organization_type'),
    sa.CheckConstraint("status IN ('draft', 'pending', 'active', 'suspended', 'deactivated')", name='organization_status'),
    sa.CheckConstraint("status IN ('draft', 'pending', 'active', 'suspended', 'deactivated')", name='organization_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('codename', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codename')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope_level', sa.Enum('system', 'organization', 'study', 'site', name='scope_level', create_constraint=True), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("scope_level IN ('system', 'organization', 'study', 'site')", name='scope_level'),
    sa.CheckConstraint("scope_level IN ('system', 'organization', 'study', 'site')", name='scope_level'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='user_status', create_constraint=True), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'suspended')", name='user_status'),
    sa.CheckConstraint("status IN ('active', 'inactive', 'suspended')", name='user_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_applications',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'under_review', 'returned', 'rejected', 'approved', name='onboarding_status', create_constraint=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'under_review', 'returned', 'rejected', 'approved')", name='onboarding_status'),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'under_review', 'returned', 'rejected', 'approved')", name='onboarding_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_members',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'removed', name='assignment_status', create_constraint=True), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'removed')", name='assignment_status'),
    sa.CheckConstraint("status IN ('active', 'inactive', 'removed')", name='assignment_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_organization_members_user_organization')
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', 'id')
    )
    op.create_table('sites',
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('site_type', sa.Enum('hospital', 'clinic', 'research_center', 'academic', 'other', name='site_type', create_constraint=True), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='site_status', create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("site_type IN ('hospital', 'clinic', 'research_center', 'academic', 'other')", name='site_type'),
    sa.CheckConstraint("site_type IN ('hospital', 'clinic', 'research_center', 'academic', 'other')", name='site_type'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='site_status'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='site_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_site_code'), 'sites', ['site_code'], unique=True)
    op.create_table('studies',
    sa.Column('study_code', sa.String(length=50), nullable=False),
    sa.Column('protocol_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('short_title', sa.String(length=200), nullable=True),
    sa.Column('study_type', sa.Enum('interventional', 'observational', 'expanded_access', name='study_type', create_constraint=True), nullable=False),
    sa.Column('phase', sa.Enum('phase_1', 'phase_1_2', 'phase_2', 'phase_2_3', 'phase_3', 'phase_3_4', 'phase_4', 'na', name='study_phase', create_constraint=True), nullable=False),
    sa.Column('sponsor_org_id', sa.Uuid(), nullable=False),
    sa.Column('cro_org_id', sa.Uuid(), nullable=True),
    sa.Column('therapeutic_area', sa.String(length=200), nullable=False),
    sa.Column('intervention_type', sa.String(length=200), nullable=True),
    sa.Column('study_design', sa.String(length=200), nullable=True),
    sa.Column('blinding', sa.Enum('open_label', 'single_blind', 'double_blind', 'triple_blind', name='blinding_type', create_constraint=True), nullable=True),
    sa.Column('randomization', sa.Boolean(), nullable=True),
    sa.Column('planned_sample_size', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('recruitment_start_date', sa.Date(), nullable=True),
    sa.Column('recruitment_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'planned', 'active', 'suspended', 'completed', 'terminated', 'withdrawn', name='study_status', create_constraint=True), nullable=False),
    sa.Column('ctri_status', sa.Enum('not_registered', 'pending', 'registered', name='ctri_status', create_constraint=True), nullable=True),
    sa.Column('ctri_number', sa.String(length=50), nullable=True),
    sa.Column('ec_approval_status', sa.Enum('not_submitted', 'pending', 'approved', 'conditional', 'rejected', name='study_ec_approval_status', create_constraint=True), nullable=True),
    sa.Column('regulatory_status', sa.Enum('not_submitted', 'pending', 'approved', 'conditional', 'rejected', name='study_regulatory_status', create_constraint=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("blinding IN ('open_label', 'single_blind', 'double_blind', 'triple_blind')", name='blinding_type'),
    sa.CheckConstraint("blinding IN ('open_label', 'single_blind', 'double_blind', 'triple_blind')", name='blinding_type'),
    sa.CheckConstraint("ctri_status IN ('not_registered', 'pending', 'registered')", name='ctri_status'),
    sa.CheckConstraint("ctri_status IN ('not_registered', 'pending', 'registered')", name='ctri_status'),
    sa.CheckConstraint("ec_approval_status IN ('not_submitted', 'pending', 'approved', 'conditional', 'rejected')", name='study_ec_approval_status'),
    sa.CheckConstraint("ec_approval_status IN ('not_submitted', 'pending', 'approved', 'conditional', 'rejected')", name='study_ec_approval_status'),
    sa.CheckConstraint("phase IN ('phase_1', 'phase_1_2', 'phase_2', 'phase_2_3', 'phase_3', 'phase_3_4', 'phase_4', 'na')", name='study_phase'),
    sa.CheckConstraint("phase IN ('phase_1', 'phase_1_2', 'phase_2', 'phase_2_3', 'phase_3', 'phase_3_4', 'phase_4', 'na')", name='study_phase'),
    sa.CheckConstraint("regulatory_status IN ('not_submitted', 'pending', 'approved', 'conditional', 'rejected')", name='study_regulatory_status'),
    sa.CheckConstraint("regulatory_status IN ('not_submitted', 'pending', 'approved', 'conditional', 'rejected')", name='study_regulatory_status'),
    sa.CheckConstraint("status IN ('draft', 'planned', 'active', 'suspended', 'completed', 'terminated', 'withdrawn')", name='study_status'),
    sa.CheckConstraint("status IN ('draft', 'planned', 'active', 'suspended', 'completed', 'terminated', 'withdrawn')", name='study_status'),
    sa.CheckConstraint("study_type IN ('interventional', 'observational', 'expanded_access')", name='study_type'),
    sa.CheckConstraint("study_type IN ('interventional', 'observational', 'expanded_access')", name='study_type'),
    sa.ForeignKeyConstraint(['cro_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sponsor_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studies_cro_org_id'), 'studies', ['cro_org_id'], unique=False)
    op.create_index(op.f('ix_studies_ctri_number'), 'studies', ['ctri_number'], unique=False)
    op.create_index(op.f('ix_studies_protocol_number'), 'studies', ['protocol_number'], unique=True)
    op.create_index(op.f('ix_studies_sponsor_org_id'), 'studies', ['sponsor_org_id'], unique=False)
    op.create_index(op.f('ix_studies_study_code'), 'studies', ['study_code'], unique=True)
    op.create_table('documents',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('study_id', sa.Uuid(), nullable=True),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('document_type', sa.Enum('protocol', 'investigator_brochure', 'icf', 'ec_document', 'regulatory', 'contract', 'training', 'essential', 'other', name='document_type', create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('draft', 'under_review', 'approved', 'superseded', 'expired', 'archived', name='document_status', create_constraint=True), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("document_type IN ('protocol', 'investigator_brochure', 'icf', 'ec_document', 'regulatory', 'contract', 'training', 'essential', 'other')", name='document_type'),
    sa.CheckConstraint("document_type IN ('protocol', 'investigator_brochure', 'icf', 'ec_document', 'regulatory', 'contract', 'training', 'essential', 'other')", name='document_type'),
    sa.CheckConstraint("status IN ('draft', 'under_review', 'approved', 'superseded', 'expired', 'archived')", name='document_status'),
    sa.CheckConstraint("status IN ('draft', 'under_review', 'approved', 'superseded', 'expired', 'archived')", name='document_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_expiry_date'), 'documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_documents_study_id'), 'documents', ['study_id'], unique=False)
    op.create_table('ethics_approvals',
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('committee_name', sa.String(length=300), nullable=False),
    sa.Column('approval_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('not_submitted', 'pending', 'approved', 'conditional', 'rejected', 'expired', name='ec_approval_status', create_constraint=True), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('not_submitted', 'pending', 'approved', 'conditional', 'rejected', 'expired')", name='ec_approval_status'),
    sa.CheckConstraint("status IN ('not_submitted', 'pending', 'approved', 'conditional', 'rejected', 'expired')", name='ec_approval_status'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ethics_approvals_expiry_date'), 'ethics_approvals', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_ethics_approvals_study_id'), 'ethics_approvals', ['study_id'], unique=False)
    op.create_table('participants',
    sa.Column('participant_code', sa.String(length=50), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('screened', 'eligible', 'screen_failed', 'randomized', 'enrolled', 'active', 'completed', 'withdrawn', 'discontinued', name='participant_status', create_constraint=True), nullable=False),
    sa.Column('screening_date', sa.Date(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('randomization_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('withdrawal_date', sa.Date(), nullable=True),
    sa.Column('withdrawal_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('screened', 'eligible', 'screen_failed', 'randomized', 'enrolled', 'active', 'completed', 'withdrawn', 'discontinued')", name='participant_status'),
    sa.CheckConstraint("status IN ('screened', 'eligible', 'screen_failed', 'randomized', 'enrolled', 'active', 'completed', 'withdrawn', 'discontinued')", name='participant_status'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_participant_code'), 'participants', ['participant_code'], unique=True)
    op.create_index(op.f('ix_participants_site_id'), 'participants', ['site_id'], unique=False)
    op.create_index(op.f('ix_participants_study_id'), 'participants', ['study_id'], unique=False)
    op.create_table('regulatory_submissions',
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('submission_type', sa.String(length=200), nullable=False),
    sa.Column('authority', sa.String(length=300), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('not_submitted', 'pending', 'approved', 'conditional', 'rejected', name='reg_submission_status', create_constraint=True), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('not_submitted', 'pending', 'approved', 'conditional', 'rejected')", name='reg_submission_status'),
    sa.CheckConstraint("status IN ('not_submitted', 'pending', 'approved', 'conditional', 'rejected')", name='reg_submission_status'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_submissions_study_id'), 'regulatory_submissions', ['study_id'], unique=False)
    op.create_table('study_milestones',
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'delayed', 'cancelled', name='milestone_status', create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'delayed', 'cancelled')", name='milestone_status'),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'delayed', 'cancelled')", name='milestone_status'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_milestones_study_id'), 'study_milestones', ['study_id'], unique=False)
    op.create_table('study_sites',
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('activation_status', sa.Enum('planned', 'initiated', 'activated', 'suspended', 'closed', name='study_site_activation_status', create_constraint=True), nullable=False),
    sa.Column('ec_status', sa.Enum('not_submitted', 'pending', 'approved', 'conditional', 'rejected', 'expired', name='study_site_ec_status', create_constraint=True), nullable=True),
    sa.Column('contract_status', sa.Enum('not_started', 'negotiating', 'executed', 'terminated', name='study_site_contract_status', create_constraint=True), nullable=True),
    sa.Column('recruitment_target', sa.Integer(), nullable=True),
    sa.Column('monitoring_status', sa.Enum('not_started', 'ongoing', 'completed', name='monitoring_status', create_constraint=True), nullable=True),
    sa.Column('activation_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("activation_status IN ('planned', 'initiated', 'activated', 'suspended', 'closed')", name='study_site_activation_status'),
    sa.CheckConstraint("activation_status IN ('planned', 'initiated', 'activated', 'suspended', 'closed')", name='study_site_activation_status'),
    sa.CheckConstraint("contract_status IN ('not_started', 'negotiating', 'executed', 'terminated')", name='study_site_contract_status'),
    sa.CheckConstraint("contract_status IN ('not_started', 'negotiating', 'executed', 'terminated')", name='study_site_contract_status'),
    sa.CheckConstraint("ec_status IN ('not_submitted', 'pending', 'approved', 'conditional', 'rejected', 'expired')", name='study_site_ec_status'),
    sa.CheckConstraint("ec_status IN ('not_submitted', 'pending', 'approved', 'conditional', 'rejected', 'expired')", name='study_site_ec_status'),
    sa.CheckConstraint("monitoring_status IN ('not_started', 'ongoing', 'completed')", name='monitoring_status'),
    sa.CheckConstraint("monitoring_status IN ('not_started', 'ongoing', 'completed')", name='monitoring_status'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'site_id', name='uq_study_sites_study_site')
    )
    op.create_index(op.f('ix_study_sites_site_id'), 'study_sites', ['site_id'], unique=False)
    op.create_index(op.f('ix_study_sites_study_id'), 'study_sites', ['study_id'], unique=False)
    op.create_table('study_team_members',
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('assignment_status', sa.Enum('active', 'inactive', 'removed', name='team_assignment_status', create_constraint=True), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("assignment_status IN ('active', 'inactive', 'removed')", name='team_assignment_status'),
    sa.CheckConstraint("assignment_status IN ('active', 'inactive', 'removed')", name='team_assignment_status'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_team_members_study_id'), 'study_team_members', ['study_id'], unique=False)
    op.create_index(op.f('ix_study_team_members_user_id'), 'study_team_members', ['user_id'], unique=False)
    op.create_table('adverse_events',
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('ae', 'sae', 'susar', name='adverse_event_type', create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('onset_date', sa.Date(), nullable=False),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('seriousness', sa.Enum('non_serious', 'serious', name='ae_seriousness', create_constraint=True), nullable=False),
    sa.Column('severity', sa.Enum('mild', 'moderate', 'severe', 'life_threatening', 'fatal', name='ae_severity', create_constraint=True), nullable=False),
    sa.Column('causality', sa.Enum('unrelated', 'unlikely', 'possible', 'probable', 'definite', name='ae_causality', create_constraint=True), nullable=True),
    sa.Column('expectedness', sa.Enum('expected', 'unexpected', name='ae_expectedness', create_constraint=True), nullable=True),
    sa.Column('action_taken', sa.String(length=500), nullable=True),
    sa.Column('outcome', sa.Enum('recovered', 'recovering', 'not_recovered', 'fatal', 'unknown', name='ae_outcome', create_constraint=True), nullable=True),
    sa.Column('reporting_deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'under_review', 'closed', name='ae_status', create_constraint=True), nullable=False),
    sa.Column('reported_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("causality IN ('unrelated', 'unlikely', 'possible', 'probable', 'definite')", name='ae_causality'),
    sa.CheckConstraint("causality IN ('unrelated', 'unlikely', 'possible', 'probable', 'definite')", name='ae_causality'),
    sa.CheckConstraint("event_type IN ('ae', 'sae', 'susar')", name='adverse_event_type'),
    sa.CheckConstraint("event_type IN ('ae', 'sae', 'susar')", name='adverse_event_type'),
    sa.CheckConstraint("expectedness IN ('expected', 'unexpected')", name='ae_expectedness'),
    sa.CheckConstraint("expectedness IN ('expected', 'unexpected')", name='ae_expectedness'),
    sa.CheckConstraint("outcome IN ('recovered', 'recovering', 'not_recovered', 'fatal', 'unknown')", name='ae_outcome'),
    sa.CheckConstraint("outcome IN ('recovered', 'recovering', 'not_recovered', 'fatal', 'unknown')", name='ae_outcome'),
    sa.CheckConstraint("seriousness IN ('non_serious', 'serious')", name='ae_seriousness'),
    sa.CheckConstraint("seriousness IN ('non_serious', 'serious')", name='ae_seriousness'),
    sa.CheckConstraint("severity IN ('mild', 'moderate', 'severe', 'life_threatening', 'fatal')", name='ae_severity'),
    sa.CheckConstraint("severity IN ('mild', 'moderate', 'severe', 'life_threatening', 'fatal')", name='ae_severity'),
    sa.CheckConstraint("status IN ('open', 'under_review', 'closed')", name='ae_status'),
    sa.CheckConstraint("status IN ('open', 'under_review', 'closed')", name='ae_status'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adverse_events_participant_id'), 'adverse_events', ['participant_id'], unique=False)
    op.create_index(op.f('ix_adverse_events_site_id'), 'adverse_events', ['site_id'], unique=False)
    op.create_index(op.f('ix_adverse_events_study_id'), 'adverse_events', ['study_id'], unique=False)
    op.create_table('protocol_deviations',
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('participant_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('minor', 'major', 'critical', name='deviation_severity', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('identified', 'reported', 'resolved', name='deviation_status', create_constraint=True), nullable=False),
    sa.Column('identified_date', sa.Date(), nullable=False),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("severity IN ('minor', 'major', 'critical')", name='deviation_severity'),
    sa.CheckConstraint("severity IN ('minor', 'major', 'critical')", name='deviation_severity'),
    sa.CheckConstraint("status IN ('identified', 'reported', 'resolved')", name='deviation_status'),
    sa.CheckConstraint("status IN ('identified', 'reported', 'resolved')", name='deviation_status'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_deviations_study_id'), 'protocol_deviations', ['study_id'], unique=False)
    op.create_table('capa_records',
    sa.Column('study_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('deviation_id', sa.Uuid(), nullable=True),
    sa.Column('capa_type', sa.Enum('corrective', 'preventive', name='capa_type', create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'completed', 'verified', name='capa_status', create_constraint=True), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("capa_type IN ('corrective', 'preventive')", name='capa_type'),
    sa.CheckConstraint("capa_type IN ('corrective', 'preventive')", name='capa_type'),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'completed', 'verified')", name='capa_status'),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'completed', 'verified')", name='capa_status'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deviation_id'], ['protocol_deviations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capa_records_study_id'), 'capa_records', ['study_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capa_records_study_id'), table_name='capa_records')
    op.drop_table('capa_records')
    op.drop_index(op.f('ix_protocol_deviations_study_id'), table_name='protocol_deviations')
    op.drop_table('protocol_deviations')
    op.drop_index(op.f('ix_adverse_events_study_id'), table_name='adverse_events')
    op.drop_index(op.f('ix_adverse_events_site_id'), table_name='adverse_events')
    op.drop_index(op.f('ix_adverse_events_participant_id'), table_name='adverse_events')
    op.drop_table('adverse_events')
    op.drop_index(op.f('ix_study_team_members_user_id'), table_name='study_team_members')
    op.drop_index(op.f('ix_study_team_members_study_id'), table_name='study_team_members')
    op.drop_table('study_team_members')
    op.drop_index(op.f('ix_study_sites_study_id'), table_name='study_sites')
    op.drop_index(op.f('ix_study_sites_site_id'), table_name='study_sites')
    op.drop_table('study_sites')
    op.drop_index(op.f('ix_study_milestones_study_id'), table_name='study_milestones')
    op.drop_table('study_milestones')
    op.drop_index(op.f('ix_regulatory_submissions_study_id'), table_name='regulatory_submissions')
    op.drop_table('regulatory_submissions')
    op.drop_index(op.f('ix_participants_study_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_site_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_participant_code'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_ethics_approvals_study_id'), table_name='ethics_approvals')
    op.drop_index(op.f('ix_ethics_approvals_expiry_date'), table_name='ethics_approvals')
    op.drop_table('ethics_approvals')
    op.drop_index(op.f('ix_documents_study_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_expiry_date'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_studies_study_code'), table_name='studies')
    op.drop_index(op.f('ix_studies_sponsor_org_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_protocol_number'), table_name='studies')
    op.drop_index(op.f('ix_studies_ctri_number'), table_name='studies')
    op.drop_index(op.f('ix_studies_cro_org_id'), table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_sites_site_code'), table_name='sites')
    op.drop_table('sites')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_table('onboarding_applications')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('organizations')
    # ### end Alembic commands ###
