"""initial_cro_sponsor_schema

Revision ID: 35f75b6f0684
Revises:
Create Date: 2026-10-05 15:59:44.233318

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "35f75b6f0684"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
