"""add super admin onboarding

Revision ID: dd212c6996cd
Revises: 35f75b6f0684
Create Date: 2026-10-06 17:30:02.233772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd212c6996cd'
down_revision: Union[str, None] = '35f75b6f0684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_requests',
    sa.Column('applicant_name', sa.String(length=255), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('organization_type', sa.Enum('cro', 'sponsor', 'institution', 'site_affiliate', name='organization_type'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'under_review', 'approved', 'rejected', 'changes_requested', name='onboarding_request_status', create_constraint=True), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('provisioned_organization_id', sa.Uuid(), nullable=True),
    sa.Column('provisioned_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'under_review', 'approved', 'rejected', 'changes_requested')", name='onboarding_request_status'),
    sa.CheckConstraint("status IN ('pending', 'under_review', 'approved', 'rejected', 'changes_requested')", name='onboarding_request_status'),
    sa.ForeignKeyConstraint(['provisioned_organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['provisioned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('super_admin_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bootstrapped_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'must_change_password')
    op.drop_table('super_admin_profiles')
    op.drop_table('onboarding_requests')
    op.drop_table('invitation_tokens')
    # ### end Alembic commands ###
