import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  BadgeCheck,
  Building,
  Building2,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Database,
  Download,
  Eye,
  File,
  FileCheck,
  FileSpreadsheet,
  FileText,
  Filter,
  Folder,
  HelpCircle,
  Info,
  Layers,
  LayoutDashboard,
  Lock,
  LogOut,
  Menu,
  MoreVertical,
  Plus,
  RefreshCw,
  Search,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Stethoscope,
  TrendingUp,
  Upload,
  User,
  UserCheck,
  UserPlus,
  Users,
  X,
  XCircle,
} from 'lucide-react'

export const iconRegistry = {
  // Navigation & Actions
  search: Search,
  plus: Plus,
  close: X,
  check: Check,
  filter: Filter,
  menu: Menu,
  moreVertical: MoreVertical,
  'more-vertical': MoreVertical,
  refresh: RefreshCw,
  download: Download,
  upload: Upload,
  eye: Eye,
  arrowRight: ArrowRight,
  'arrow-right': ArrowRight,
  chevronDown: ChevronDown,
  'chevron-down': ChevronDown,
  chevronUp: ChevronUp,
  'chevron-up': ChevronUp,
  chevronLeft: ChevronLeft,
  'chevron-left': ChevronLeft,
  chevronRight: ChevronRight,
  'chevron-right': ChevronRight,

  // Domain Entities
  dashboard: LayoutDashboard,
  organization: Building2,
  building: Building,
  study: Layers,
  site: Building,
  participant: User,
  participants: Users,
  adverseEvent: ShieldAlert,
  compliance: ShieldCheck,
  documents: Folder,
  document: FileText,
  'file-text': FileText,
  documentCheck: FileCheck,
  spreadsheet: FileSpreadsheet,
  file: File,
  audit: Database,
  database: Database,
  users: Users,
  userPlus: UserPlus,
  'user-plus': UserPlus,
  userCheck: UserCheck,
  'user-check': UserCheck,
  shieldAlert: ShieldAlert,
  'shield-alert': ShieldAlert,
  shieldCheck: ShieldCheck,
  'shield-check': ShieldCheck,

  // Status & Feedback
  success: CheckCircle2,
  warning: AlertTriangle,
  alert: AlertTriangle,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  error: XCircle,
  danger: AlertCircle,
  info: Info,
  help: HelpCircle,
  clock: Clock,
  calendar: Calendar,
  activity: Activity,
  trendingUp: TrendingUp,
  'trending-up': TrendingUp,
  badgeCheck: BadgeCheck,
  lock: Lock,
  logout: LogOut,
  stethoscope: Stethoscope,
  shield: Shield,
}

export type IconName = keyof typeof iconRegistry
